//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsApiSeat.WsEncuestasPSI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Encuesta", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    public partial class Encuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEncuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsApiSeat.WsEncuestasPSI.Mensaje MensajeControlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsApiSeat.WsEncuestasPSI.Plantilla PlantillaEncuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdArea {
            get {
                return this.IdAreaField;
            }
            set {
                if ((this.IdAreaField.Equals(value) != true)) {
                    this.IdAreaField = value;
                    this.RaisePropertyChanged("IdArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdCompania {
            get {
                return this.IdCompaniaField;
            }
            set {
                if ((this.IdCompaniaField.Equals(value) != true)) {
                    this.IdCompaniaField = value;
                    this.RaisePropertyChanged("IdCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEncuesta {
            get {
                return this.IdEncuestaField;
            }
            set {
                if ((this.IdEncuestaField.Equals(value) != true)) {
                    this.IdEncuestaField = value;
                    this.RaisePropertyChanged("IdEncuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsApiSeat.WsEncuestasPSI.Mensaje MensajeControl {
            get {
                return this.MensajeControlField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeControlField, value) != true)) {
                    this.MensajeControlField = value;
                    this.RaisePropertyChanged("MensajeControl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsApiSeat.WsEncuestasPSI.Plantilla PlantillaEncuesta {
            get {
                return this.PlantillaEncuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantillaEncuestaField, value) != true)) {
                    this.PlantillaEncuestaField = value;
                    this.RaisePropertyChanged("PlantillaEncuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsApiSeat.WsEncuestasPSI.MensajeAgradecimiento))]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoMensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsError {
            get {
                return this.EsErrorField;
            }
            set {
                if ((this.EsErrorField.Equals(value) != true)) {
                    this.EsErrorField = value;
                    this.RaisePropertyChanged("EsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoError {
            get {
                return this.TextoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoErrorField, value) != true)) {
                    this.TextoErrorField = value;
                    this.RaisePropertyChanged("TextoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoMensaje {
            get {
                return this.TextoMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoMensajeField, value) != true)) {
                    this.TextoMensajeField = value;
                    this.RaisePropertyChanged("TextoMensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plantilla", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    public partial class Plantilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlantillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePlantillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsApiSeat.WsEncuestasPSI.Pregunta[] PreguntasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoDePrimerContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlantilla {
            get {
                return this.IdPlantillaField;
            }
            set {
                if ((this.IdPlantillaField.Equals(value) != true)) {
                    this.IdPlantillaField = value;
                    this.RaisePropertyChanged("IdPlantilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePlantilla {
            get {
                return this.NombrePlantillaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePlantillaField, value) != true)) {
                    this.NombrePlantillaField = value;
                    this.RaisePropertyChanged("NombrePlantilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsApiSeat.WsEncuestasPSI.Pregunta[] Preguntas {
            get {
                return this.PreguntasField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntasField, value) != true)) {
                    this.PreguntasField = value;
                    this.RaisePropertyChanged("Preguntas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoDePrimerContacto {
            get {
                return this.TextoDePrimerContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoDePrimerContactoField, value) != true)) {
                    this.TextoDePrimerContactoField = value;
                    this.RaisePropertyChanged("TextoDePrimerContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoEntrada {
            get {
                return this.TextoEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoEntradaField, value) != true)) {
                    this.TextoEntradaField = value;
                    this.RaisePropertyChanged("TextoEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeAgradecimiento", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    public partial class MensajeAgradecimiento : wsApiSeat.WsEncuestasPSI.Mensaje {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PreguntaContactarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoAgradecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoAgradecimientoGenericoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreguntaContactar {
            get {
                return this.PreguntaContactarField;
            }
            set {
                if ((this.PreguntaContactarField.Equals(value) != true)) {
                    this.PreguntaContactarField = value;
                    this.RaisePropertyChanged("PreguntaContactar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoAgradecimiento {
            get {
                return this.TextoAgradecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoAgradecimientoField, value) != true)) {
                    this.TextoAgradecimientoField = value;
                    this.RaisePropertyChanged("TextoAgradecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoAgradecimientoGenerico {
            get {
                return this.TextoAgradecimientoGenericoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoAgradecimientoGenericoField, value) != true)) {
                    this.TextoAgradecimientoGenericoField = value;
                    this.RaisePropertyChanged("TextoAgradecimientoGenerico");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pregunta", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    public partial class Pregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PrioridadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wsApiSeat.WsEncuestasPSI.Respuesta[] RespuestasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoEscalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoPreguntaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdPregunta {
            get {
                return this.IdPreguntaField;
            }
            set {
                if ((this.IdPreguntaField.Equals(value) != true)) {
                    this.IdPreguntaField = value;
                    this.RaisePropertyChanged("IdPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Prioridad {
            get {
                return this.PrioridadField;
            }
            set {
                if ((this.PrioridadField.Equals(value) != true)) {
                    this.PrioridadField = value;
                    this.RaisePropertyChanged("Prioridad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsApiSeat.WsEncuestasPSI.Respuesta[] Respuestas {
            get {
                return this.RespuestasField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestasField, value) != true)) {
                    this.RespuestasField = value;
                    this.RaisePropertyChanged("Respuestas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoEscala {
            get {
                return this.TextoEscalaField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoEscalaField, value) != true)) {
                    this.TextoEscalaField = value;
                    this.RaisePropertyChanged("TextoEscala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoPregunta {
            get {
                return this.TextoPreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoPreguntaField, value) != true)) {
                    this.TextoPreguntaField = value;
                    this.RaisePropertyChanged("TextoPregunta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/wsPSI_APP")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdTipoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRespuesta {
            get {
                return this.IdRespuestaField;
            }
            set {
                if ((this.IdRespuestaField.Equals(value) != true)) {
                    this.IdRespuestaField = value;
                    this.RaisePropertyChanged("IdRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdTipoRespuesta {
            get {
                return this.IdTipoRespuestaField;
            }
            set {
                if ((this.IdTipoRespuestaField.Equals(value) != true)) {
                    this.IdTipoRespuestaField = value;
                    this.RaisePropertyChanged("IdTipoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoRespuesta {
            get {
                return this.TextoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoRespuestaField, value) != true)) {
                    this.TextoRespuestaField = value;
                    this.RaisePropertyChanged("TextoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRespuesta {
            get {
                return this.TipoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRespuestaField, value) != true)) {
                    this.TipoRespuestaField = value;
                    this.RaisePropertyChanged("TipoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsEncuestasPSI.IServicioPSI_APP")]
    public interface IServicioPSI_APP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/ObtenerPlantillaEncuesta", ReplyAction="http://tempuri.org/IServicioPSI_APP/ObtenerPlantillaEncuestaResponse")]
        wsApiSeat.WsEncuestasPSI.Encuesta ObtenerPlantillaEncuesta(int idEncuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/ObtenerPlantillaEncuesta", ReplyAction="http://tempuri.org/IServicioPSI_APP/ObtenerPlantillaEncuestaResponse")]
        System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.Encuesta> ObtenerPlantillaEncuestaAsync(int idEncuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/GuardarEncuesta", ReplyAction="http://tempuri.org/IServicioPSI_APP/GuardarEncuestaResponse")]
        wsApiSeat.WsEncuestasPSI.MensajeAgradecimiento GuardarEncuesta(wsApiSeat.WsEncuestasPSI.Encuesta encuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/GuardarEncuesta", ReplyAction="http://tempuri.org/IServicioPSI_APP/GuardarEncuestaResponse")]
        System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.MensajeAgradecimiento> GuardarEncuestaAsync(wsApiSeat.WsEncuestasPSI.Encuesta encuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/GuardaDeseaSerContactado", ReplyAction="http://tempuri.org/IServicioPSI_APP/GuardaDeseaSerContactadoResponse")]
        wsApiSeat.WsEncuestasPSI.Mensaje GuardaDeseaSerContactado(int idEncuesta, bool contactar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPSI_APP/GuardaDeseaSerContactado", ReplyAction="http://tempuri.org/IServicioPSI_APP/GuardaDeseaSerContactadoResponse")]
        System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.Mensaje> GuardaDeseaSerContactadoAsync(int idEncuesta, bool contactar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPSI_APPChannel : wsApiSeat.WsEncuestasPSI.IServicioPSI_APP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPSI_APPClient : System.ServiceModel.ClientBase<wsApiSeat.WsEncuestasPSI.IServicioPSI_APP>, wsApiSeat.WsEncuestasPSI.IServicioPSI_APP {
        
        public ServicioPSI_APPClient() {
        }
        
        public ServicioPSI_APPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPSI_APPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPSI_APPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPSI_APPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wsApiSeat.WsEncuestasPSI.Encuesta ObtenerPlantillaEncuesta(int idEncuesta) {
            return base.Channel.ObtenerPlantillaEncuesta(idEncuesta);
        }
        
        public System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.Encuesta> ObtenerPlantillaEncuestaAsync(int idEncuesta) {
            return base.Channel.ObtenerPlantillaEncuestaAsync(idEncuesta);
        }
        
        public wsApiSeat.WsEncuestasPSI.MensajeAgradecimiento GuardarEncuesta(wsApiSeat.WsEncuestasPSI.Encuesta encuesta) {
            return base.Channel.GuardarEncuesta(encuesta);
        }
        
        public System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.MensajeAgradecimiento> GuardarEncuestaAsync(wsApiSeat.WsEncuestasPSI.Encuesta encuesta) {
            return base.Channel.GuardarEncuestaAsync(encuesta);
        }
        
        public wsApiSeat.WsEncuestasPSI.Mensaje GuardaDeseaSerContactado(int idEncuesta, bool contactar) {
            return base.Channel.GuardaDeseaSerContactado(idEncuesta, contactar);
        }
        
        public System.Threading.Tasks.Task<wsApiSeat.WsEncuestasPSI.Mensaje> GuardaDeseaSerContactadoAsync(int idEncuesta, bool contactar) {
            return base.Channel.GuardaDeseaSerContactadoAsync(idEncuesta, contactar);
        }
    }
}
